server:
  port: 3060
db:
  password: cambiar!!
log:
  req: false
  db:
    on-demand: true
install:
  dump:
    #drop-his: true
  table-data-dir: 
    - ../dmencu-data/repsic252
    - ../dmencu-data/templates_app_final #no borrar, dejar último, chequea los tabs obligatorios al correr -- --dump-db
login:
  plus:
    secret: 39djjfnvvjas..33.3.33
    allowHttpLogin: true
devel:
  forceShowAsEditable: false
  useFileDevelopment: true
client-setup:
  skin: ""
  lang: es